# Generated by Django 5.2.16 on 2026-07-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cash_on_delivery',
            field=models.BooleanField(default=True, help_text='Allow customers to pay for this product with Cash on Delivery.'),
        ),
        migrations.AddField(
            model_name='product',
            name='free_shipping',
            field=models.BooleanField(default=True, help_text='If enabled, this product ships for free. If disabled, set a shipping charge below.'),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Shipping amount charged for this product when Free Shipping is disabled.', max_digits=8),
        ),
    ]
