# Generated by Django 6.0.7 on 2026-07-25 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_cash_on_delivery_product_free_shipping_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinquiry',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='reply',
            field=models.TextField(blank=True, help_text="Admin's reply, shown to the user in their account."),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Auto-linked to the logged-in user who submitted this, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_inquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='cash_on_delivery',
            field=models.BooleanField(default=True, help_text='Allow customers to pay with Cash on Delivery.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='free_shipping',
            field=models.BooleanField(default=True, help_text='If enabled, this product ships for free.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Shipping amount charged when Free Shipping is disabled.', max_digits=8),
        ),
    ]
